language: node_js
node_js:
  - "node"
cache:
  directories:
  - node_modules
script:
  - npm install
  - npm test
  - CI=false npm run build
after_success:
  - npm install -g firebase-tools
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive