language: node_js
node_js:
  - "10.16.3"
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run build
after_success:
  - npm install -g firebase-tools
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive